debug = true

[server]
port = 3000
site = "http://localhost:3000"

[pgsql]
host = "localhost"
port = 5432
username = "username"
password = "password"
database = "doulog"

[redis]
host = "localhost"
port = 6379
auth = ""
database = 0

[auth]
# 前端 callback url prefixs
# front-end callback url prefixs
frontend_callback_prefix = ['http://localhost:5432']

[auth.github]
# GitHub OAuth2 配置
# GitHub OAuth2 Config
client_id = ""
client_secret = ""
